### ISSUE TITLE
I have  got a forbidden error during collect the revenue information

### ISSUE THREAD

**Issue by NaveenSelva-95** [Prem-ium/youtube-analytics-bot#3]
`googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtubeanalytics.googleapis.com/v2/reports?ids=channel%3D%3DMINE&startDate=2023-01-01&endDate=2023-04-11&metrics=views%2CestimatedMinutesWatched%2CsubscribersGained%2CsubscribersLost%2CestimatedRevenue%2Ccpm%2CmonetizedPlaybacks%2CplaybackBasedCpm%2CadImpressions%2Clikes%2Cdislikes%2CaverageViewDuration%2Cshares%2CaverageViewPercentage%2CsubscribersGained%2CsubscribersLost&alt=json returned "Forbidden">`

**Comment by Prem-ium** [comment]
Hello @NaveenSelva-95,

This error may have something to do with a missing scope on your credentials file. On Google Cloud Platform, try to verify you have the added scopes to your YouTube Analytics Project API that give you permission to read and access analytics.

They should be something along the lines of these two scopes:

"https://www.googleapis.com/auth/youtube.readonly",
"https://www.googleapis.com/auth/yt-analytics-monetary.readonly"

Make sure you put enable them when you generate your client secret json on the Google Cloud website.
